  - name: List files (debug)
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type d -name dist -print -o -name build -print

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/**
            **/dist/**
            build/**
            **/build/**
          if-no-files-found: error
